job/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

from content.views import FullSearchView

urlpatterns = list()

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    url(r'^', include('job_catalog.urls', namespace='catalog')),
    url(r'^', include('content.urls', namespace='content')),
    url(r'^admin/', admin.site.urls),

    url(r'^search/', FullSearchView.as_view(), name='search'),
    url(r'^accounts/', include('users.accounts_urls')),
    url(r'^profile/', include('users.urls', namespace='profile')),
    url(r'^banner/', include('banner.urls', namespace='banner')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^polls/', include('poll.urls', namespace='poll')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

job_catalog/urls.py
from django.conf.urls import url

from job_catalog.forms import CVModelAndRegistrationForm
from job_catalog.models import CV, Vacancy
from job_catalog.views import IndexView, CreateAdvertRegistrationView, VacancyAndRegistrationForm, CreateCVView, \
    CreateVacancyView, MyCvList, MyVacancyList, CVEditView, VacancyEditView, GetCvInfo, GetVacancyInfo, ReplySuccess, \
    ReplyCv, ReplyVacancy, AddToFavorites, DeleteFromFavorites, MyFavorites, ToPrint
from yandex_job.views import YandexJobGate

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^create_cv_unregister/$', CreateAdvertRegistrationView.as_view(form_class=CVModelAndRegistrationForm,
                                                                         model=CV), name='cv_unregister'),
    url(r'^create_vacancy_unregister/$', CreateAdvertRegistrationView.as_view(form_class=VacancyAndRegistrationForm,
                                                                              model=Vacancy,
                                                                              template_name='create_vacancy.html'),
        name='vacancy_unregister'),
    url(r'^create_cv/$', CreateCVView.as_view(), name='cv_create'),
    url(r'^create_vacancy/$', CreateVacancyView.as_view(), name='vacancy_create'),
    url(r'^my_cv/$', MyCvList.as_view(), name='my_cv_list'),
    url(r'^my_vacancies/$', MyVacancyList.as_view(), name='my_vac_list'),
    url(r'^update_cv/(?P<pk>\d+)/$', CVEditView.as_view(), name='update_cv'),
    url(r'^update_vacancies/(?P<pk>\d+)/$', VacancyEditView.as_view(), name='update_vacancy'),
    url(r'^get_cv_info/(?P<pk>\d+)/$', GetCvInfo.as_view(), name='get_cv_info'),
    url(r'^get_vacancy_info/(?P<pk>\d+)/$', GetVacancyInfo.as_view(), name='get_vacancy_info'),
    url(r'^reply_cv/(?P<pk>\d+)/$', ReplyCv.as_view(), name='cv_reply'),
    url(r'^reply_vacancy/(?P<pk>\d+)/$', ReplyVacancy.as_view(), name='vac_reply'),
    url(r'^success_reply/$', ReplySuccess.as_view(), name='success_reply'),
    url(r'^add_to_fav/(?P<slug>\w+)/(?P<pk>\d+)/$', AddToFavorites.as_view(), name='add_fav'),
    url(r'^delete_to_fav/(?P<slug>\w+)/(?P<pk>\d+)/$', DeleteFromFavorites.as_view(), name='delete_fav'),
    url(r'^my_favorites/$', MyFavorites.as_view(), name='my_fav'),
    url(r'^to_print/(?P<slug>\w+)/(?P<pk>\d+)/$', ToPrint.as_view(), name='to_print'),
    url(r'^vacancy_gate/$', YandexJobGate.as_view()),
]

users/urls.py
from django.conf.urls import url

from users.views import ProfileView, ProfileChangePhoto, ProfileUpdate, SubscribeCreateView, MySubscribesListView, \
    MySubscribeDeleteView

urlpatterns = [
    url(r'^$', ProfileView.as_view(), name='profile'),
    url(r'^update_profile/$', ProfileUpdate.as_view(), name='profile_update'),
    url(r'^set_photo/$', ProfileChangePhoto.as_view(), name='profile_set_photo'),
    url(r'^create_subscribe/$', SubscribeCreateView.as_view(), name='create_subscribe'),
    url(r'^my_subscribes/$', MySubscribesListView.as_view(), name='my_subscribes'),
    url(r'^delete_subscribe/(?P<pk>\d+)/$', MySubscribeDeleteView.as_view(), name='delete_subscribe'),
]

users/models.py
from datetime import date

from ckeditor.fields import RichTextField
from django.contrib.auth.models import (AbstractBaseUser, PermissionsMixin)
from django.contrib.auth.models import UserManager
from django.core.cache import cache
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import send_mail
from django.db import models
from django.db.models import EmailField
from django.template import Template, Context
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from sorl.thumbnail import ImageField
from django.utils import timezone

from .tasks import subscribe_send_mail

SUBSCRIBE_TYPE = (
    (0, 'Вакансии'),
    (1, 'Резюме')
)


class User(AbstractBaseUser, PermissionsMixin):
    email = EmailField(verbose_name='Email', unique=True)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    favorites_vacancies = models.ManyToManyField('job_catalog.Vacancy', verbose_name='Избранные вакансии',
                                                 related_name='fav_vac', null=True)
    favorites_cv = models.ManyToManyField('job_catalog.CV', verbose_name='Избранные резюме', related_name='fav_cv',
                                          null=True)

    USERNAME_FIELD = 'email'

    objects = UserManager()

    def get_favorite_vacancies(self):
        return self.favorites_vacancies.filter(status=2, profile__user__is_active=True)

    def get_favorite_cv(self):
        return self.favorites_cv.filter(status=2, profile__user__is_active=True)

    def set_favorites_ids(self):
        fav_cv_ids = self.get_favorite_cv().values_list('pk', flat=True)
        fav_vac_ids = self.get_favorite_vacancies().values_list('pk', flat=True)
        if fav_vac_ids or fav_cv_ids:
            data = {'cv': fav_cv_ids, 'vac': fav_vac_ids}
        else:
            data = {}
        cache.set(settings.FAVORITE_ID_LIST_USER.format(self.pk), data, 3600)
        return data

    def get_favorites_ids(self):
        data = cache.get(settings.FAVORITE_ID_LIST_USER.format(self.pk), None)
        if data is not None:
            return data
        else:
            return self.set_favorites_ids()

    def set_favorite_count(self):
        cvs = self.get_favorite_cv().count()
        vacancy = self.get_favorite_vacancies().count()
        result = cvs + vacancy
        cache.set(settings.FAVORITE_COUNT_USER.format(self.pk), result, 3600)
        return result

    def get_favorite_count(self):
        ad_count = cache.get(settings.FAVORITE_COUNT_USER.format(self.pk), None)
        if ad_count is not None:
            return ad_count
        else:
            return self.set_favorite_count()

    @property
    def profile_employer(self):
        try:
            profile = self.employer_profile
            return profile
        except ObjectDoesNotExist:
            return None

    @property
    def profile_applicant(self):
        try:
            profile = self.applicant_profile
            return profile
        except ObjectDoesNotExist:
            return None

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def get_short_name(self):
        return self.email

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'


class EmployerProfile(models.Model):
    phone = models.CharField(verbose_name='Телефон', max_length=20, null=True, blank=True)
    logo = ImageField(verbose_name='Фото', null=True, blank=True, upload_to='logos')
    company = models.CharField(verbose_name='Название компании', max_length=255, null=True, blank=True)
    contact = models.CharField(verbose_name='Контактное лицо', max_length=255, null=True, blank=True)
    address = models.CharField(verbose_name='Адрес компании', max_length=300)
    user = models.OneToOneField(User, verbose_name='Пользователь', related_name='employer_profile')
    employer_day = models.BooleanField(verbose_name='Работодатель дня', default=False)

    def __str__(self):
        return self.user.email

    class Meta:
        verbose_name = 'Профиль работодателя'
        verbose_name_plural = 'Профили работодателей'


class ApplicantProfile(models.Model):
    phone = models.CharField(verbose_name='Телефон', max_length=20, null=True, blank=True)
    photo = ImageField(verbose_name='Фото', null=True, blank=True, upload_to='logos')
    first_name = models.CharField(verbose_name='Имя', max_length=255, null=True, blank=True)
    last_name = models.CharField(verbose_name='Фамилия', max_length=255, null=True, blank=True)
    third_name = models.CharField(verbose_name='Отчество', max_length=255, null=True, blank=True)
    birth_day = models.DateField(verbose_name='День рождения', null=True, blank=True)
    user = models.OneToOneField(User, verbose_name='Пользователь', related_name='applicant_profile')

    def __str__(self):
        return self.user.email

    def years(self):
        today = date.today()
        return today.year - self.birth_day.year - ((today.month, today.day) < (self.birth_day.month,
                                                                               self.birth_day.day))

    class Meta:
        verbose_name = 'Профиль соискателя'
        verbose_name_plural = 'Профили соискателей'


class Subscribe(models.Model):
    user = models.ForeignKey(User, verbose_name='Пользователь', related_name='subscribes')
    category = models.ForeignKey('job_catalog.Category', verbose_name='Категория')
    subscribe_type = models.SmallIntegerField(verbose_name='Тип подписки', choices=SUBSCRIBE_TYPE, default=0)

    def send_message(self, adv_list):
        if adv_list:
            if self.subscribe_type == 0:
                context = {'vac_list': adv_list, 'category': self.category.name if self.category else None}
                subject = 'Новые вакансии по вашей подписке, на сайте "Кадры города"'
            else:
                context = {'cv_list': adv_list, 'category': self.category.name if self.category else None}
                subject = 'Новые резюме по вашей подписке, на сайте "Кадры города"'
            template = SubscribeTemplate.objects.filter(slug=self.subscribe_type).first()
            if template:
                tpl = template.create_template(context)
                subscribe_send_mail.delay(subject, tpl, self.user.email)


class SubscribeTemplate(models.Model):
    slug = models.SmallIntegerField(verbose_name='Тип подписки', choices=SUBSCRIBE_TYPE, default=0, unique=True)
    template = RichTextField(verbose_name='Шаблон')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return self.get_slug_display()

    def create_template(self, ctx):
        tpl = Template(self.template)
        template = tpl.render(Context(ctx))
        return template

    class Meta:
        verbose_name = 'Шаблон рассылки'
        verbose_name_plural = 'Шаблоны рассылки'

templates/profile/my_subscribe_list.html
{% extends 'index.html' %}
{% block center_line %}
    <h1>Мои подписки</h1>
    <div class="src_result col16">
        {% for subscribe in object_list %}
            <div class="one_line">
                    <div class="col13">
                        <div class="row ol_head">
                            <div class="col10">
                                <h4>{{ subscribe.category.name }}</h4>
                            </div>
                            <div class="col6 right">
                                <p class="p14">{{ subscribe.get_subscribe_type_display }}</p>
                            </div>
                        </div>
                        <div class="ol_icos">
                            <div class="col5"><a href="{% url 'profile:delete_subscribe' subscribe.pk %}">Удалить</a></div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

{% endblock %}

templates/profile/profile_applicant.html
{% extends 'index.html' %}
{% load ads_tags %}
{% block center_line %}
    <div class="my_list_page">
        <div class="my_list_head">
            <div class="pullright right">
                <a href="{% url 'catalog:my_cv_list' %}" class="my_vac">Мои резюме</a>
                <a href="{% url 'profile:my_subscribes' %}" class="my_vac">Мои подписки</a>
                <a href="{% url 'catalog:my_fav' %}" class="my_fav">Избранные вакансии</a>
            </div>
        </div>
        <div class="clear"></div>
        <div class="my_list_body">
            <div class="row">
                <div class="col4 ml_photo">
                    {% if profile.photo %}
                        <img src="{{ MEDIA_URL }}{{ profile.photo }}" alt="">
                    {% else %}
                        <img src="{{ STATIC_URL }}img/conp_def.jpg" alt="">
                    {% endif %}
                    <a href="#" class="p14 js_trigger">Загрузить фото</a>
                </div>
                <div class="col12 ml_descr">
                    <div class="pullright">
                        <a href="{% url 'profile:profile_update' %}" class="ml_edit">Редактировать профиль</a>
                        <a href="{% url 'password_change' %}" class="ml_edit">Сменить пароль</a>
                    </div>
                    <p class="p18">{{ profile.last_name|default:"" }} {{ profile.first_name|default:"" }} {{ profile.third_name|default:"" }}</p>
                    {% if profile.birth_day %}
                        <p class="p14">{{ profile.years }} года ({{ profile.birth_day}})</p>
                    {% endif %}
                    {% if profile.phone %}
                        <p><a href="tel:{{ profile.phone }}" class="ml_phone p14">{{ profile.phone }}</a></p>
                    {% endif %}
                    <p><a href="mailto:{{ request.user.email }}" class="ml_mail p14">{{ request.user.email }}</a></p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block modal %}
    <div class="modal" id="test-modal" style="display: none">
		<a href="#" class="close"><img src="{{ STATIC_URL }}img/cross.png" alt=""></a>
		<div>
			<form method="POST" id="form_1" class="formv" action="{% url 'profile:profile_set_photo' %}"
                  enctype="multipart/form-data">
                {% csrf_token %}
                <input type="file" name="photo">
                <button type="submit" class="wide_yellow">Сменить фото</button>
			</form>
		</div>
    </div>
    {% get_categories as categories %}
    <div class="modal" id="subscribe-modal" style="display: none">
		<a href="#" class="close"><img src="{{ STATIC_URL }}img/cross.png" alt=""></a>
		<div>
			<form method="POST" id="form_1" class="formv" action="{% url 'profile:create_subscribe' %}"
                  enctype="multipart/form-data">
                {% csrf_token %}
                <input type="hidden" name="redirect" value="{{ request.path }}">
                <label for="slug">
                    Тип подписки
                </label>
                <select name="slug" id="slug">
                    <option value="0">Вакансии</option>
                    <option value="1">Резюме</option>
                </select>
                <label for="category">
                    Сфера деятельности
                </label>
                <select name="category" id="">
                    {% for cat in categories.cat_list %}
                        <option value="{{ cat.pk }}">{{ cat.name }}</option>
                    {% endfor %}
                </select>
                <button type="submit" class="wide_yellow">Подписаться</button>
			</form>
		</div>
    </div>
{% endblock %}

templates/profile/profile_edit_applicant.html
{% extends 'index.html' %}
{% block center_line %}
    <h1>Администратор участка в вахтовый поселок</h1>
    <div class="my_list_page">
        <div class="my_list_head">
            <div class="pullright right">
                <a href="{% url 'catalog:my_cv_list' %}" class="my_vac">Мои резюме</a>
                <a href="{% url 'profile:my_subscribes' %}" class="my_vac">Мои подписки</a>
                <a href="{% url 'catalog:my_fav' %}" class="my_fav">Избранные вакансии</a>
            </div>
        </div>
        <div class="clear"></div>
        <div class="my_list_body">
            <div class="row">
                <div class="col4 ml_photo">
                    {% if object.photo %}
                        <img src="{{ MEDIA_URL }}{{ object.photo }}" alt="">
                    {% else %}
                        <img src="{{ STATIC_URL }}img/conp_def.jpg" alt="">
                    {% endif %}
                    <a href="#" class="p14 js_trigger">Загрузить фото</a>
                </div>
                <div class="col12 ml_descr">
                    <div class="pullright">
                        <a href="{% url 'profile:profile' %}" class="ml_edit">Профиль</a>
                        <a href="{% url 'password_change' %}" class="ml_edit">Сменить пароль</a>
                    </div>
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ form.errors }}
                        {% for field in form %}
                            <div>
                                <label for="">{{ field.label }}</label>
                                {{ field }}
                                {% for err in field.errors %}
                                    <p>{{ err }}</p>
                                {% endfor %}
                            </div>
                        {% endfor %}
                        <input type="submit" value="Сохранить">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block modal %}
    <div class="modal" id="test-modal" style="display: none">
		<a href="#" class="close"><img src="{{ STATIC_URL }}img/cross.png" alt=""></a>
		<div>
			<form method="POST" id="form_1" class="formv" action="{% url 'profile:profile_set_photo' %}"
                  enctype="multipart/form-data">
                {% csrf_token %}
                <input type="file" name="photo">
                <button type="submit" class="wide_yellow">Сменить фото</button>
			</form>
		</div>
    </div>
{% endblock %}

templates/profile/profile_edit_employer.html
{% extends 'index.html' %}
{% block center_line %}
    <h1>{{ object.company }}</h1>
    <div class="my_list_page">
        <div class="my_list_head">
            <div class="pullright right">
                <a href="{% url 'catalog:my_vac_list' %}" class="my_vac">Мои вакансии</a>
                <a href="{% url 'profile:my_subscribes' %}" class="my_vac">Мои подписки</a>
                <a href="{% url 'catalog:my_fav' %}" class="my_fav">Избранные резюме</a>
            </div>
        </div>
        <div class="clear"></div>
        <div class="my_list_body">
            <div class="row">
                <div class="col4 ml_photo">
                    {% if profile.logo %}
                        <img src="{{ MEDIA_URL }}{{ object.logo }}" alt="">
                    {% else %}
                        <img src="{{ STATIC_URL }}img/conp_def.jpg" alt="">
                    {% endif %}
                    <a href="#" class="p14 js_trigger">Загрузить фото</a>
                </div>
                <div class="col12 ml_descr">
                    <div class="pullright">
                        <a href="{% url 'profile:profile' %}" class="ml_edit">Редактировать профиль</a>
                        <a href="{% url 'password_change' %}" class="ml_edit">Сменить пароль</a>
                    </div>
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ form.errors }}
                        {% for field in form %}
                            <div>
                                <label for="">{{ field.label }}</label>
                                {{ field }}
                                {% for err in field.errors %}
                                    <p>{{ err }}</p>
                                {% endfor %}
                            </div>
                        {% endfor %}
                        <input type="submit" value="Сохранить">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block modal %}
    <div class="modal" id="test-modal" style="display: none">
		<a href="#" class="close"><img src="{{ STATIC_URL }}img/cross.png" alt=""></a>
		<div>
			<form method="POST" id="form_1" class="formv" action="{% url 'profile:profile_set_photo' %}"
                  enctype="multipart/form-data">
                {% csrf_token %}
                <input type="file" name="photo">
                <button type="submit" class="wide_yellow">Сменить фото</button>
			</form>
		</div>
    </div>
{% endblock %}

templates/profile/profile_employer.html
{% extends 'index.html' %}
{% load ads_tags %}
{% block center_line %}
    <h1>{{ profile.company }}</h1>
    <div class="my_list_page">
        <div class="my_list_head">
            <div class="pullright right">
                <a href="{% url 'catalog:my_vac_list' %}" class="my_vac">Мои вакансии</a>
                <a href="{% url 'profile:my_subscribes' %}" class="my_vac">Мои подписки</a>
                <a href="{% url 'catalog:my_fav' %}" class="my_fav">Избранные резюме</a>
            </div>
        </div>
        <div class="clear"></div>
        <div class="my_list_body">
            <div class="row">
                <div class="col4 ml_photo">
                    {% if profile.logo %}
                        <img src="{{ MEDIA_URL }}{{ profile.logo }}" alt="">
                    {% else %}
                        <img src="{{ STATIC_URL }}img/conp_def.jpg" alt="">
                    {% endif %}
                    <a href="#" class="p14 js_trigger">Загрузить фото</a>
                </div>
                <div class="col12 ml_descr">
                    <div class="pullright">
                        <!--<a href="{% url 'profile:profile_update' %}" class="ml_edit">Редактировать профиль</a>
                        <a href="{% url 'password_change' %}" class="ml_edit">Сменить пароль</a>-->
                    </div>
                    <p class="p18">{{ profile.contact|default:"" }}</p>
                    <p class="p14">{{ profile.address|default:"" }}</p>
                    <p><a href="tel:{{ profile.phone|default:"" }}" class="ml_phone p14">{{ profile.phone|default:"" }}</a></p>
                    <p><a href="mailto:{{ request.user.email }}" class="ml_mail p14">{{ request.user.email }}</a></p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block modal %}
    <div class="modal" id="test-modal" style="display: none">
		<a href="#" class="close"><img src="{{ STATIC_URL }}img/cross.png" alt=""></a>
		<div>
			<form method="POST" id="form_1" class="formv" action="{% url 'profile:profile_set_photo' %}"
                  enctype="multipart/form-data">
                {% csrf_token %}
                <input type="file" name="photo">
                <button type="submit" class="wide_yellow">Сменить фото</button>
			</form>
		</div>
    </div>
    {% get_categories as categories %}
    <div class="modal" id="subscribe-modal" style="display: none">
		<a href="#" class="close"><img src="{{ STATIC_URL }}img/cross.png" alt=""></a>
		<div>
			<form method="POST" id="form_1" class="formv" action="{% url 'profile:create_subscribe' %}"
                  enctype="multipart/form-data">
                {% csrf_token %}
                <input type="hidden" name="redirect" value="{{ request.path }}">
                <label for="slug">
                    Тип подписки
                </label>
                <select name="slug" id="slug">
                    <option value="0">Вакансии</option>
                    <option value="1">Резюме</option>
                </select>
                <label for="category">
                    Сфера деятельности
                </label>
                <select name="category" id="">
                    {% for cat in categories.cat_list %}
                        <option value="{{ cat.pk }}">{{ cat.name }}</option>
                    {% endfor %}
                </select>
                <button type="submit" class="wide_yellow">Подписаться</button>
			</form>
		</div>
    </div>
{% endblock %}