job/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

from content.views import FullSearchView

urlpatterns = list()

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    url(r'^', include('job_catalog.urls', namespace='catalog')),
    url(r'^', include('content.urls', namespace='content')),
    url(r'^admin/', admin.site.urls),

    url(r'^search/', FullSearchView.as_view(), name='search'),
    url(r'^accounts/', include('users.accounts_urls')),
    url(r'^profile/', include('users.urls', namespace='profile')),
    url(r'^banner/', include('banner.urls', namespace='banner')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^polls/', include('poll.urls', namespace='poll')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

poll/urls.py
from django.conf.urls import url

from poll.views import PollIndexView, VoteAddView, AllPollListView

urlpatterns = [
    url(r'^$', PollIndexView.as_view(), name='index'),
    url(r'^all_polls$', AllPollListView.as_view(), name='polls_list'),
    url(r'^vote/(?P<pk>\d+)/$', VoteAddView.as_view(), name='vote'),
]

poll/models.py
import math
from django.core.cache import cache
from django.db import models
from django.db.models import Sum
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver


class PollManager(models.Manager):

    def get_active_polls(self):
        return self.filter(active=True)


class Poll(models.Model):
    name = models.CharField(verbose_name='Название', max_length=255)
    active = models.BooleanField(verbose_name='Активен', default=True)
    created = models.DateTimeField(verbose_name='Создан', auto_now_add=True)
    multiple_choice = models.BooleanField(verbose_name='Мультивыбор', default=False)

    objects = PollManager()

    def get_results(self):
        key = settings.POLL_ID_RESULT.format(self.pk)
        result = cache.get(key)
        if result:
            return result
        else:
            return self.set_results()

    def set_results(self):
        votes = self.votes.all()
        counts = self.votes.all().aggregate(total_counts=Sum('count'))['total_counts']
        results = {'count': counts, 'votes': list()}
        for vote in votes:
            result = dict()
            if counts:
                result['percent'] = math.floor((vote.count / counts) * 100)
            else:
                result['percent'] = 0
            result['count'] = vote.count
            result['name'] = vote.name
            results['votes'].append(result)
        key = settings.POLL_ID_RESULT.format(self.pk)
        cache.set(key, results, 3600)
        return results

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Опрос'
        verbose_name_plural = 'Опросы'
        ordering = ['-created']


class PollVote(models.Model):
    poll = models.ForeignKey(Poll, verbose_name='Опрос', related_name='votes')
    name = models.CharField(verbose_name='Название', max_length=150)
    count = models.PositiveIntegerField(verbose_name='Счетчик голосов', default=0)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Вариант ответа'
        verbose_name_plural = 'Варианты ответов'
        ordering = ['pk']


@receiver(post_save, sender=PollVote)
def save_vote(sender, instance, **kwargs):
    instance.poll.set_results()

poll/views.py
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.base import View
from pure_pagination import PaginationMixin

from job.utils import json_response, MenuMixin
from poll.models import Poll, PollVote
from poll.utils import get_votes_cookies


class PollIndexView(MenuMixin, TemplateView):
    template_name = 'polls/poll_index.html'
    menu_slug = 'poll'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        polls = Poll.objects.get_active_polls()
        polls_complete = get_votes_cookies(self.request.COOKIES.get('polls_vote', []))
        if polls_complete:
            active_poll = polls.exclude(pk__in=polls_complete).first()
        else:
            active_poll = polls.first()
        ctx['open_vote'] = active_poll
        return ctx


class AllPollListView(MenuMixin, PaginationMixin, ListView):
    template_name = 'polls/all_polls.html'
    queryset = Poll.objects.get_active_polls().prefetch_related('votes')
    paginate_by = 10
    menu_slug = 'poll'


class VoteAddView(View):

    def post(self, request, *args, **kwargs):
        pk = kwargs.get('pk')
        vote_pk = request.POST.getlist('vote')
        polls_cookie = get_votes_cookies(self.request.COOKIES.get('polls_vote', []))
        if pk and vote_pk and pk.isdigit() and pk not in polls_cookie:
            poll = Poll.objects.get_active_polls().filter(pk=pk).first()
            if poll.multiple_choice:
                votes = PollVote.objects.filter(poll=poll, pk__in=vote_pk)
                for vote in votes:
                    vote.count += 1
                    vote.save(update_fields=['count'])
            else:
                vote = PollVote.objects.filter(poll=poll, pk=vote_pk[0]).first()
                if poll and vote:
                    vote.count += 1
                    vote.save(update_fields=['count'])
            data = {'result': True}
            polls_cookie.append(poll.pk)
            response = json_response(data)
            response.set_cookie('polls_vote', polls_cookie)
            return response
        else:
            data = {'result': False}
            return json_response(data)

templates/polls/_poll_complete_detail_form.html
<div class="quest_blc_big">
    <div class="new_feat_in quest_blc">
        <p class="p16">{{ poll.name }}</p>
        {% for vote in poll.get_results.votes %}
            <div class="qs_res_one">
                <p class="p13">{{ vote.name }} (<b>{{ vote.percent }}%, {{ vote.count }}</b> по голосам)</p>
                <div class="progress_bar" data-size="{{ vote.percent }}%" style="width: {{ vote.percent }}%;"></div>
            </div>
        {% endfor %}
        <p class="p12">Всего проголосовавших: <b>{{ poll.get_results.count }}</b> человек </p>

    </div>
</div>

templates/polls/_poll_detail_form.html
<div class="quest_blc_big" id="poll_card_{{ poll.pk }}">
    <div class="new_feat_in quest_blc">
        <p class="p16">{{ poll.name }}</p>
        <form action="{% url 'poll:vote' poll.pk %}" class="vote_form" id="vote_form_{{ poll.pk }}">
            {% csrf_token %}
            {% if poll.multiple_choice %}
                {% for vote in poll.votes.all %}
                    <div>
                        <input type="checkbox" name="vote" value="{{ vote.pk }}" id="vote_{{ vote.pk }}">
                        <label for="vote_{{ vote.pk }}">{{ vote.name }}</label>
                    </div>
                {% endfor %}
            {% else %}
                {% for vote in poll.votes.all %}
                    <div>
                        <input type="radio" name="vote" value="{{ vote.pk }}" id="vote_{{ vote.pk }}">
                        <label for="vote_{{ vote.pk }}">{{ vote.name }}</label>
                    </div>
                {% endfor %}
            {% endif %}
            <button class="btn_black" data-form-id="{{ poll.pk }}" type="button">Проголосовать</button>
        </form>
        {% if show_link %}
            <a href="{% url 'poll:polls_list' %}">Посмотреть все опросы</a>
        {% endif %}
    </div>
</div>

templates/polls/_poll_for_footer.html
<h3>Опрос</h3>
<p class="p16">{{ poll.name }}</p>
{% if view == 'form' %}
<form action="{% url 'poll:vote' poll.pk %}" class="vote_form" id="vote_form_{{ poll.pk }}">
        {% csrf_token %}
        {% if poll.multiple_choice %}
            {% for vote in poll.votes.all %}
                <div>
                    <input type="checkbox" name="vote" value="{{ vote.pk }}" id="vote_{{ vote.pk }}">
                    <label for="vote_{{ vote.pk }}">{{ vote.name }}</label>
                </div>
            {% endfor %}
        {% else %}
            {% for vote in poll.votes.all %}
                <div>
                    <input type="radio" name="vote" value="{{ vote.pk }}" id="vote_{{ vote.pk }}">
                    <label for="vote_{{ vote.pk }}">{{ vote.name }}</label>
                </div>
            {% endfor %}
        {% endif %}
        <button class="btn_black" data-form-id="{{ poll.pk }}" type="button">Проголосовать</button>
</form>
{% else %}
    {% for vote in poll.get_results.votes %}
        <div class="qs_res_one">
            <p class="p13">{{ vote.name }} (<b>{{ vote.percent }}%, {{ vote.count }}</b> по голосам)</p>
            <div class="progress_bar" data-size="{{ vote.percent }}%" style="width: {{ vote.percent }}%;"></div>
        </div>
    {% endfor %}
    <p class="p12">Всего проголосовавших: <b>{{ poll.get_results.count }}</b> человек </p>
{% endif %}
<div class="center">
    <a href="{% url 'poll:polls_list' %}">Посмотреть все опросы</a>
</div>

templates/polls/all_polls.html
{% extends 'index.html' %}
{% load polls_tags %}
{% block center_line %}
    <h1>Результаты опросов</h1>
    <div class="ask_page">
        {% for poll in object_list  %}
            {% is_vote poll.pk request as user_vote %}
            {% if not user_vote %}
                {% render_poll_detail_form poll False %}
            {% else %}
                {% render_poll_detail_result poll %}
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}
{% block pagination %}
<div class="pagination center">
    {% if page_obj.paginator.num_pages > 1 %}
        <ul>
            {% for page in page_obj.pages %}
                <li>
                    {% if page %}
                        {% ifequal page page_obj.number %}
                            <span>{{ page }}</span>
                        {% else %}
                            <a href="?{{ page.querystring }}">{{ page }}</a>
                        {% endifequal %}
                    {% else %}
                        ...
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% endif %}
</div>
{% endblock %}

templates/polls/poll_index.html
{% extends 'index.html' %}
{% load polls_tags %}
{% block center_line %}
    <h1>Опросы</h1>
    <div class="ask_page">
        <div>
            <p class="p14">Уважаемые читатели газеты «Кадры Города»!</p>
            <p class="p14">Мы клиентоориентированная газета, мы очень хотим, чтобы наше издание было не только информативным, но также интересным и читаемым. Мы постоянно совершенствуемся и развиваемся и чтобы печатать в газете то, что соответствует требованиям читателей, мы должны знать о Вас и Ваших предпочтениях как можно больше.</p>
            <p class="p14">Наши рекламодатели также хотят знать, кто составляет нашу читательскую аудиторию, каков образовательный уровень, каковы доходы, кем Вы работаете, почему читаете нашу газету.</p>
            <p class="p14">Ваше мнение очень важно для нас!</p>
        </div>
        {% if open_vote %}
            {% render_poll_detail_form open_vote %}
        {% else %}
            <a href="{% url 'poll:polls_list' %}">Посмотреть все опросы</a>
        {% endif %}
    </div>
{% endblock %}