content/urls.py
from django.conf.urls import url

from content.views import FeedBackListView, PartnerListView, EducationAdvertsListView, BirthDaysView, ArticleListView, \
    ArticleDetailView, ActionListView, ContactView, QAJuristCreateView, QAJuristDetail, QAJuristQuestionAjax, \
    NewsPaperList, PriceListView, NewsList, NewsDetail, SalaryStatList, ExpertNoteListView, ExpertNoteDetailView, \
    EventList, EventDetail

urlpatterns = [
    url(r'^feedback/$', FeedBackListView.as_view(), name='feedback'),
    url(r'^partners/$', PartnerListView.as_view(), name='partners'),
    url(r'^education/$', EducationAdvertsListView.as_view(), name='education'),
    url(r'^partner_birth_day/$', BirthDaysView.as_view(), name='birth_day'),
    url(r'^articles/$', ArticleListView.as_view(), name='articles'),
    url(r'^article/(?P<slug>[-\w]+)/$', ArticleDetailView.as_view(), name='article'),
    url(r'^actions/$', ActionListView.as_view(), name='actions'),
    url(r'^contacts/$', ContactView.as_view(), name='contacts'),
    url(r'^qa/$', QAJuristDetail.as_view(), name='qa_detail'),
    url(r'^qa/(?P<pk>\d+)/$', QAJuristDetail.as_view(), name='qa_detail'),
    url(r'^qa_detail/(?P<year>\d+)/$', QAJuristQuestionAjax.as_view(), name='qa_year'),
    url(r'^qa_create/$', QAJuristCreateView.as_view(), name='qa_create'),
    url(r'^archive/$', NewsPaperList.as_view(), name='archive'),
    url(r'^prices/$', PriceListView.as_view(), name='prices'),
    url(r'^news/$', NewsList.as_view(), name='news_list'),
    url(r'^news/(?P<slug>[-\w]+)/$', NewsDetail.as_view(), name='news'),
    url(r'^salary_stats/(?P<year>\d+)/$', SalaryStatList.as_view(), name='stat_list_year'),
    url(r'^salary_stats/$', SalaryStatList.as_view(), name='stat_list'),
    url(r'^mnenie-eksperta/$', ExpertNoteListView.as_view(), name='expert_note_list'),
    url(r'^mnenie-eksperta/(?P<slug>[-\w]+)/$', ExpertNoteDetailView.as_view(), name='expert_note'),
    url(r'^events/$', EventList.as_view(), name='events'),
    url(r'^events/(?P<slug>[-\w]+)/$', EventDetail.as_view(), name='event'),
]

job/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

from content.views import FullSearchView

urlpatterns = list()

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    url(r'^', include('job_catalog.urls', namespace='catalog')),
    url(r'^', include('content.urls', namespace='content')),
    url(r'^admin/', admin.site.urls),

    url(r'^search/', FullSearchView.as_view(), name='search'),
    url(r'^accounts/', include('users.accounts_urls')),
    url(r'^profile/', include('users.urls', namespace='profile')),
    url(r'^banner/', include('banner.urls', namespace='banner')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^polls/', include('poll.urls', namespace='poll')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

content/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms

from content.models import Feedback, QAJurist


class FeedBackAdminForm(forms.ModelForm):
    text = forms.CharField(label='Текст отзыва', widget=CKEditorWidget())

    class Meta:
        model = Feedback
        fields = '__all__'


class EducationAdminForm(forms.ModelForm):
    text = forms.CharField(label='Текст', widget=CKEditorWidget())

    class Meta:
        model = Feedback
        fields = '__all__'


class QAJuristAdminForm(forms.ModelForm):
    answer = forms.CharField(label='Ответ', widget=CKEditorWidget())

    class Meta:
        model = QAJurist
        fields = '__all__'

content/views.py
import datetime

from django.contrib import messages
from django.http import Http404
from django.urls import reverse_lazy, reverse
from django.utils.formats import date_format
from django.utils.text import Truncator
from django.views.generic import ListView, DetailView, TemplateView, CreateView
from django.views.generic.base import View
from pure_pagination import PaginationMixin
from watson.views import SearchView

from content.models import Feedback, Partner, Education, CongratulationsPartner, Article, Action, QAJurist, NewsPaper, \
    PriceList, News, SalaryStat, ExpertNote, Event
from job.utils import json_response, MenuMixin
from job_catalog.models import Category


class FeedBackListView(MenuMixin, PaginationMixin, ListView):
    paginate_by = 10
    template_name = 'content/feedback_list.html'
    queryset = Feedback.objects.all().order_by('-created')
    context_object_name = 'feedback_list'
    menu_slug = 'feed'


class PartnerListView(MenuMixin, PaginationMixin, ListView):
    paginate_by = 12
    template_name = 'content/partner_list.html'
    queryset = Partner.objects.all()
    context_object_name = 'partner_list'
    menu_slug = 'partners'


class EducationAdvertsListView(MenuMixin, PaginationMixin, ListView):
    paginate_by = 10
    template_name = 'content/edu_list.html'
    queryset = Education.objects.filter(active=True)
    context_object_name = 'edu_list'
    menu_slug = 'edu'


class FullSearchView(SearchView):
    template_name = "search/search_results.html"

    def get_models(self):
        return (Education.objects.filter(active=True),
                Partner.objects.all(),
                Feedback.objects.all())


class BirthDaysView(MenuMixin, PaginationMixin, ListView):
    paginate_by = 200
    template_name = 'content/birth_day_list.html'
    menu_slug = 'birthday'

    def get_verbose_month(self):
        today = datetime.date.today()
        if today.month == 1:
            return 'январе'
        elif today.month == 2:
            return 'феврале'
        elif today.month == 3:
            return 'марте'
        elif today.month == 4:
            return 'апреле'
        elif today.month == 5:
            return 'мае'
        elif today.month == 6:
            return 'июне'
        elif today.month == 7:
            return 'июле'
        elif today.month == 8:
            return 'августе'
        elif today.month == 9:
            return 'сентябре'
        elif today.month == 10:
            return 'октябре'
        elif today.month == 11:
            return 'ноябре'
        elif today.month == 12:
            return 'декабре'

    def get_queryset(self):
        today = datetime.date.today()
        objects = CongratulationsPartner.objects.filter(birth_day__month=today.month)
        return objects

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['month'] = self.get_verbose_month()
        return ctx


class ArticleListView(MenuMixin, PaginationMixin, ListView):
    paginate_by = 10
    queryset = Article.objects.filter(published=True)
    template_name = 'content/article_list.html'
    menu_slug = 'posts'


class ArticleDetailView(MenuMixin, DetailView):
    template_name = 'content/article_detail.html'
    queryset = Article.objects.filter(published=True)
    menu_slug = 'posts'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        obj.views += 1
        obj.save(update_fields=['views'])
        return obj


class ActionListView(MenuMixin, PaginationMixin, ListView):
    template_name = 'content/actions.html'
    paginate_by = 10
    queryset = Action.objects.filter(published=True)
    menu_slug = 'actions'


class ContactView(MenuMixin, TemplateView):
    template_name = 'content/contacts.html'
    menu_slug = 'contact'


class QAJuristDetail(MenuMixin, TemplateView):
    template_name = 'content/qa_detail.html'
    menu_slug = 'qa'

    def get_queryset(self):
        if self.kwargs.get('pk'):
            try:
                qs = QAJurist.objects.get_published_qa().get(pk=self.kwargs['pk'])
            except QAJurist.DoesNotExist:
                raise Http404
        else:
            qs = QAJurist.objects.get_published_qa().first()
            if not qs:
                return QAJurist.objects.none()
        return qs

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['object'] = self.get_queryset()
        ctx['years'] = QAJurist.objects.get_years()
        ctx['qa_list'] = QAJurist.objects.get_qa_current_year()
        return ctx


class QAJuristCreateView(MenuMixin, CreateView):
    template_name = 'content/qa_form.html'
    model = QAJurist
    fields = ['question']
    success_url = reverse_lazy('content:qa_detail')
    menu_slug = 'qa'

    def form_valid(self, form):
        messages.add_message(self.request, messages.INFO, 'Вопрос успешно создан!')
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['years'] = QAJurist.objects.get_years()
        ctx['qa_list'] = QAJurist.objects.get_qa_current_year()
        return ctx


class QAJuristQuestionAjax(View):

    def get(self, request, *args, **kwargs):
        data = list()
        questions = QAJurist.objects.get_year_answers(kwargs.get('year')).values('created', 'question', 'pk')
        for question in questions:
            truncated_text = Truncator(question['question']).words(10)
            link = reverse('content:qa_detail', kwargs={'pk': question['pk']})
            q = {'created': date_format(question['created'], 'd E Y'), 'link': link, 'text': truncated_text}
            data.append(q)
        return json_response(data)


class NewsPaperList(MenuMixin, PaginationMixin, ListView):
    template_name = 'content/news_paper_list.html'
    queryset = NewsPaper.objects.all()
    paginate_by = 9
    menu_slug = 'archive'


class PriceListView(MenuMixin, PaginationMixin, ListView):
    template_name = 'content/price_list.html'
    queryset = PriceList.objects.all()
    paginate_by = 6
    menu_slug = 'prices'


class NewsList(MenuMixin, PaginationMixin, ListView):
    template_name = 'content/news_list.html'
    queryset = News.objects.filter(published=True)
    paginate_by = 10
    menu_slug = 'news'


class NewsDetail(MenuMixin, DetailView):
    template_name = 'content/news.html'
    queryset = News.objects.filter(published=True)
    paginate_by = 10
    menu_slug = 'news'


class SalaryStatList(MenuMixin, PaginationMixin, ListView):
    template_name = 'content/salary_stat_list.html'
    queryset = SalaryStat.objects.all()
    years = None
    menu_slug = 'stat'

    def get_queryset(self):
        self.years = SalaryStat.objects.get_years()
        if self.kwargs.get('year'):
            year = self.kwargs.get('year')
        elif self.years.exists():
            year = self.years.first().year
        else:
            year = datetime.date.today().year
        category_pk = None
        if self.request.GET.get('category') and self.request.GET['category'].isdigit():
            category_pk = self.request.GET['category']
        return SalaryStat.objects.search(year, category=category_pk, profession=self.request.GET.get('profession'))

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['years'] = self.years
        ctx['categories'] = Category.objects.all()
        ctx['current_year'] = self.kwargs.get('year')
        return ctx


class ExpertNoteListView(PaginationMixin, ListView):
    template_name = 'content/expert_note_list.html'
    queryset = ExpertNote.objects.all()
    paginate_by = 20


class ExpertNoteDetailView(DetailView):
    template_name = 'content/expert_note.html'
    queryset = ExpertNote.objects.all()


class EventList(PaginationMixin, ListView):
    template_name = 'content/event_list.html'
    queryset = Event.objects.filter(published=True)
    paginate_by = 20


class EventDetail(DetailView):
    template_name = 'content/event.html'
    queryset = Event.objects.filter(published=True)

templates/content/actions.html
{% extends 'index.html' %}
{% load thumbnail %}
{% block center_line %}
    <h1>Акции</h1>
    <div class="promo_blc">
            {% for action in object_list %}
                {% if forloop.first or forloop.counter|divisibleby:3 %}
                    <div class="row">
                {% endif %}
                <div class="col8">
                    <a data-fancybox="gallery" href="{{ MEDIA_URL }}{{ action.banner }}">
                        <img src="{{ MEDIA_URL }}{{ action.banner }}" alt="{{ action.name }}">
                    </a>
                </div>
                {% if forloop.counter|divisibleby:2 %}
                    </div>
                {% endif %}
            {% endfor %}
    </div>
{% endblock %}

templates/content/article_list.html
{% extends 'index.html' %}
{% load thumbnail %}
{% block center_line %}
    <h1>Наши статьи</h1>
    <div class="artic_feat_page">
        {% for object in object_list %}
            <div class="artic_feat_one">
                {% if object.cover %}
                    {% thumbnail object.cover "584x203" crop="center" as im %}
                        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{ object.title }}">
                    {% endthumbnail %}
                {% endif %}
                <a href="{% url 'content:article' object.slug %}"><h4>{{ object.title }}</h4></a>
                {{ object.text|safe|truncatewords:20 }}
                <div class="row artic_feat_links">
                    <div class="col4">
                        <p class="p12">{{ object.created|date:"d.m.Y" }}</p>
                    </div>
                    <div class="col8">
                        <p class="all_views">{{ object.views }} просмотров</p>
                    </div>
                    <div class="col4">
                        <a class="p14" href="{% url 'content:article' object.slug %}">Читать дальше</a>
                    </div>

                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}
{% block pagination %}
<div class="pagination center">
    {% if page_obj.paginator.num_pages > 1 %}
        <ul>
            {% for page in page_obj.pages %}
                <li>
                    {% if page %}
                        {% ifequal page page_obj.number %}
                            <span>{{ page }}</span>
                        {% else %}
                            <a href="?{{ page.querystring }}">{{ page }}</a>
                        {% endifequal %}
                    {% else %}
                        ...
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% endif %}
</div>
{% endblock %}

templates/content/birth_day_list.html
{% extends 'index.html' %}
{% load thumbnail %}
{% block center_line %}
    <h1>Знаменательные даты и события в {{ month }}!</h1>
    <div class="dates_page">
        <div class="main_date">
            <p class="p20">Уважаемые друзья, от всей души поздравляем Вас!</p>
            <p class="p16">Пусть радость и счастье,</p>
            <p class="p16">Любовь и участье – всегда освещают Ваш путь.</p>
            <p class="p16">Пусть умчатся подальше невзгоды,</p>
            <p class="p16">И поменьше обидных потерь</p>
            <p class="p16">В жизни – только «хорошей погоды»,</p>
            <p class="p16">Рядом – только надежных друзей.</p>
        </div>
        {% for birth_date in object_list %}
            <div class="other_dates">
                <p class="p14">{{ birth_date.birth_day|date:"j E" }} — {{ birth_date.name }}, {{ birth_date.sign }}.</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}
{% block pagination %}
<div class="pagination center">
    {% if page_obj.paginator.num_pages > 1 %}
        <ul>
            {% for page in page_obj.pages %}
                <li>
                    {% if page %}
                        {% ifequal page page_obj.number %}
                            <span>{{ page }}</span>
                        {% else %}
                            <a href="?{{ page.querystring }}">{{ page }}</a>
                        {% endifequal %}
                    {% else %}
                        ...
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% endif %}
</div>
{% endblock %}

templates/content/contacts.html
{% extends 'index.html' %}
{% load thumbnail %}
{% block center_line %}
    <h1>Контакты</h1>
    <div class="cont_page">
                    <div class="row">
                        <div class="col7">
                            <img src="{{ STATIC_URL }}img/cont_photo.jpg" alt="">
                        </div>
                        <div class="col9">
                            <div class="mar_bot20">
                                <p class="p14"><b>По вопросам редакционной политики обращайтесь:</b></p>
                            </div>
                            <div class="mar_bot20">
                                <p class="p14"><b>Главный редактор:</b></p>
                                <p class="p14">Несмеянова Ольга Анатольевна,</p>
                            </div>
                            <div class="mar_bot20">
                                <p class="p14"><b>тел:</b></p>
                                <p class="p14"><a href="tel:+78332210360">8(8332) 21-03-60</a></p>
                            </div>
                            <div class="mar_bot20">
                                <p class="p14"><b>Электронная почта:</b></p>
                                <p class="p14"><a href="mailto:kg@kadry-goroda.ru">kg@kadry-goroda.ru</a></p>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col16">
                            <div class="mar_bot20">
                                <p class="p14"><b>Реквизиты:</b></p>
                                <p class="p14">ИП Несмеянова Ольга Анатольевна<br>
                                    ИНН 434550249694 ОГРН 310434534100027<br>
                                    Юридический адрес: 610017, г. Киров, ул. Красноармейская, д.61 кв. 39.<br>
                                    Банковские реквизиты:<br>
                                    Р/сч № 40802810400200000415<br>
                                    в ОАО КБ «Хлынов» г. Киров<br>
                                    к/с № 30101810100000000711 БИК 043304711</p>
                            </div>
                            <div class="mar_bot20">
                                <p class="p14"><b>По вопросам размещения рекламы обращайтесь:</b></p>
                                <p class="p14">Телефоны: 8(8332)21-42-04, 21-42-08, 21-57-23<br>
                                    Тел./факс: 8(8332)21-30-28,<br>
                                    Эл.почта: kg@kadry-goroda.ru</p>
                            </div>


                            <div class="mar_bot20">
                                <p class="p14"><b>Адрес редакции:</b></p>
                                <p class="p14">610020, г. Киров, ул. К. Маркса, д.18<br>
(офисный центр «Торговые ряды на Крине»), офис 203, 204<br>
Проезд на общественном транспорте до остановки Дворец Бракосочетаний:</p>
                            </div>
                             <div class="mar_bot20">
                                <p class="p14"><b>График работы:</b></p>
                                <p class="p14">Пн-пт. 8.00-17.00, обед с 12:00 до 13:00<br>
                                    суббота и воскресенье — выходные дни.</p>
                            </div>

                        </div>
                    </div>
                </div>
{% endblock %}

templates/content/event_list.html
{% extends 'index.html' %}
{% load thumbnail %}
{% block center_line %}
    <h1>Мероприятия города</h1>
    <div class="artic_feat_page">
        {% for object in object_list %}
            <div class="artic_feat_one">
                {% if object.cover %}
                    {% thumbnail object.cover "584x203" crop="center" as im %}
                        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{ object.title }}">
                    {% endthumbnail %}
                {% endif %}
                <a href="{% url 'content:event' object.slug %}"><h4>{{ object.title }}</h4></a>
                {{ object.text|safe|truncatewords:20 }}
                <div class="row artic_feat_links">
                    <div class="col4">
                        <p class="p12">{{ object.created|date:"d.m.Y" }}</p>
                    </div>
                    <div class="col4">
                        <a class="p14" href="{% url 'content:event' object.slug %}">Читать дальше</a>
                    </div>

                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}
{% block pagination %}
<div class="pagination center">
    {% if page_obj.paginator.num_pages > 1 %}
        <ul>
            {% for page in page_obj.pages %}
                <li>
                    {% if page %}
                        {% ifequal page page_obj.number %}
                            <span>{{ page }}</span>
                        {% else %}
                            <a href="?{{ page.querystring }}">{{ page }}</a>
                        {% endifequal %}
                    {% else %}
                        ...
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% endif %}
</div>
{% endblock %}

templates/content/expert_note_list.html
{% extends 'index.html' %}
{% load thumbnail %}
{% block center_line %}
    <h1>Мнение эксперта</h1>
    <div class="artic_feat_page">
        {% for object in object_list %}
            <div class="artic_feat_one">
                <a href="{% url 'content:expert_note' object.slug %}"><h4>{{ object.title }}</h4></a>
                <div class="row artic_feat_links">
                    <div class="col4">
                        <p class="p12">{{ object.created|date:"d.m.Y" }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}
{% block pagination %}
<div class="pagination center">
    {% if page_obj.paginator.num_pages > 1 %}
        <ul>
            {% for page in page_obj.pages %}
                <li>
                    {% if page %}
                        {% ifequal page page_obj.number %}
                            <span>{{ page }}</span>
                        {% else %}
                            <a href="?{{ page.querystring }}">{{ page }}</a>
                        {% endifequal %}
                    {% else %}
                        ...
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% endif %}
</div>
{% endblock %}

templates/content/news.html
{% extends 'index.html' %}
{% load thumbnail %}
{% block center_line %}
    <h1>{{ object.title }}</h1>
    <div class="artic_one">
        {% if object.cover %}
            {% thumbnail object.cover "584x203"  as im %}
                <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{ object.title }}">
            {% endthumbnail %}
        {% endif %}
        {{ object.text|safe }}
        <div class="row artic_feat_links">
            <div class="col4">
                <p class="p12">{{ object.created|date:"d.m.Y" }}</p>
            </div>
        </div>
    </div>
{% endblock %}

templates/content/news_list.html
{% extends 'index.html' %}
{% load thumbnail %}
{% block center_line %}
    <h1>Наши новости</h1>
    <div class="artic_feat_page">
        {% for object in object_list %}
            <div class="artic_feat_one">
                <a href="{% url 'content:news' object.slug %}"><h4>{{ object.title }}</h4></a>
                {{ object.text|safe|striptags|truncatewords:20 }}
                <div class="row artic_feat_links">
                    <div class="col4">
                        <p class="p12">{{ object.created|date:"d.m.Y" }}</p>
                    </div>
                    <div class="col4">
                        <a class="p14" href="{% url 'content:news' object.slug %}">Читать дальше</a>
                    </div>

                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}
{% block pagination %}
<div class="pagination center">
    {% if page_obj.paginator.num_pages > 1 %}
        <ul>
            {% for page in page_obj.pages %}
                <li>
                    {% if page %}
                        {% ifequal page page_obj.number %}
                            <span>{{ page }}</span>
                        {% else %}
                            <a href="?{{ page.querystring }}">{{ page }}</a>
                        {% endifequal %}
                    {% else %}
                        ...
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% endif %}
</div>
{% endblock %}

templates/content/qa_detail.html
{% extends 'index.html' %}
{% load thumbnail %}
{% block css %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/jquery.custom-scrollbar.css">
{% endblock %}
{% block center_line %}
    <h1>Вопрос юристу</h1>
    <div class="jur_answer">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <div class="other_dates">
            <a href="{% url 'content:qa_create' %}">
                <span class="p40">+</span><span class="p16">Хочешь задать вопрос нашему юристу?Жми!</span>
            </a>
        </div>
        <p class="p22">{{ object.question }}</p>
        {% if object.image %}
            <img src="{{ MEDIA_URL }}{{ object.image }}" alt="{{ qa.question }}">
        {% endif %}
        {{ object.answer|safe }}
    </div>
{% endblock %}
{% block right_line %}
    <div class="jur_nav2 default-skin">
        <div class="jur_lnks">
            <p class="jur_h1">По годам:</p>
            {% for year in years %}
                <a href="{% url 'content:qa_year' year.year %}" class="qa_year_link">{{ year|date:"Y" }}</a>
            {% endfor %}
        </div>
        <div class="jur_lnk1">
            {% for qa in qa_list %}
                <a href="{% url 'content:qa_detail' qa.pk %}">
                    <p class="j_date">{{ qa.created|date:"d E Y" }}</p>
                    <p class="j_intro">{{ qa.question|truncatewords:10 }}</p>
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}
{% block bottom_js %}
    <script src="{{ STATIC_URL }}js/jquery.custom-scrollbar.js"></script>
    <script>
        $(document).ready(function() {
          $(".jur_nav2").customScrollbar();
        });
    </script>
{% endblock %}

templates/content/qa_form.html
{% extends 'index.html' %}
{% load thumbnail %}
{% block css %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/jquery.custom-scrollbar.css">
{% endblock %}
{% block center_line %}
    <h1>Задать Вопрос юристу</h1>
    <div class="jur_answer">
        <div class="col12 ml_descr">
            <form action="" method="post">
                {% csrf_token %}
                {{ form.errors }}
                {% for field in form %}
                    <div>
                        <label for="">{{ field.label }}</label>
                        {{ field }}
                        {% for err in field.errors %}
                            <p>{{ err }}</p>
                        {% endfor %}
                    </div>
                {% endfor %}
                <input type="submit" value="Задать вопрос">
            </form>
        </div>
    </div>
{% endblock %}
{% block right_line %}
    <div class="jur_nav2 default-skin">
        <div class="jur_lnks">
            <p class="jur_h1">По годам:</p>
            {% for year in years %}
                <a href="{% url 'content:qa_year' year.year %}" class="qa_year_link">{{ year|date:"Y" }}</a>
            {% endfor %}
        </div>
        <div class="jur_lnk1">
            {% for qa in qa_list %}
                <a href="{% url 'content:qa_detail' qa.pk %}">
                    <p class="j_date">{{ qa.created|date:"d E Y" }}</p>
                    <p class="j_intro">{{ qa.question|truncatewords:10 }}</p>
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/content/salary_stat_list.html
{% extends 'index.html' %}
{% load thumbnail %}
{% block center_line %}
    <h1>Исследования зарплат</h1>
    <div class="research_page">
        <div class="research_page_head">
            <p class="right p14">
                <span>По годам: </span>
                {% for year in years %}
                    <a class="{% if year == current_year %}curr_page{% endif %}" href="{% url 'content:stat_list_year' year.year %}">{{ year.year }}</a>
                {% endfor %}
            </p>
        </div>
        <div>
            <form>
                <div class="row">
                    <div class="col5">
                        <p class="p14">Сфера деятельности</p>
                    </div>
                    <div class="col11">
                        <select name="category" id="">
                            {% for category in categories %}
                                <option value="{{ category.pk }}" {% if category.pk|stringformat:'d' == request.GET.category %}selected{% endif %}>{{ category.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="row">
                    <div class="col5">
                        <p class="p14">Профессия</p>
                    </div>
                    <div class="col11">
                        <input type="text" name="profession" value="{{ request.GET.profession }}">
                    </div>
                </div>
                <div class="row">
                    <div class="pullright col5">
                        <button class="btn_yel">Поиск</button>
                    </div>
                </div>
            </form>
        </div>
        <div>
            {% for item in object_list %}
                <p class="p18">
                    Статистика для соискателей.<br>
                    Средняя зарплата "{{ item.profession }}"
                </p>
                {% thumbnail item.chart "600x300" crop="center" as im %}
                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{ item.profession }}">
                {% endthumbnail %}
            {% endfor %}
        </div>


    </div>
{% endblock %}
{% block pagination %}
<div class="pagination center">
    {% if page_obj.paginator.num_pages > 1 %}
        <ul>
            {% for page in page_obj.pages %}
                <li>
                    {% if page %}
                        {% ifequal page page_obj.number %}
                            <span>{{ page }}</span>
                        {% else %}
                            <a href="?{{ page.querystring }}">{{ page }}</a>
                        {% endifequal %}
                    {% else %}
                        ...
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% endif %}
</div>
{% endblock %}