content/urls.py
from django.conf.urls import url

from content.views import FeedBackListView, PartnerListView, EducationAdvertsListView, BirthDaysView, ArticleListView, \
    ArticleDetailView, ActionListView, ContactView, QAJuristCreateView, QAJuristDetail, QAJuristQuestionAjax, \
    NewsPaperList, PriceListView, NewsList, NewsDetail, SalaryStatList, ExpertNoteListView, ExpertNoteDetailView, \
    EventList, EventDetail

urlpatterns = [
    url(r'^feedback/$', FeedBackListView.as_view(), name='feedback'),
    url(r'^partners/$', PartnerListView.as_view(), name='partners'),
    url(r'^education/$', EducationAdvertsListView.as_view(), name='education'),
    url(r'^partner_birth_day/$', BirthDaysView.as_view(), name='birth_day'),
    url(r'^articles/$', ArticleListView.as_view(), name='articles'),
    url(r'^article/(?P<slug>[-\w]+)/$', ArticleDetailView.as_view(), name='article'),
    url(r'^actions/$', ActionListView.as_view(), name='actions'),
    url(r'^contacts/$', ContactView.as_view(), name='contacts'),
    url(r'^qa/$', QAJuristDetail.as_view(), name='qa_detail'),
    url(r'^qa/(?P<pk>\d+)/$', QAJuristDetail.as_view(), name='qa_detail'),
    url(r'^qa_detail/(?P<year>\d+)/$', QAJuristQuestionAjax.as_view(), name='qa_year'),
    url(r'^qa_create/$', QAJuristCreateView.as_view(), name='qa_create'),
    url(r'^archive/$', NewsPaperList.as_view(), name='archive'),
    url(r'^prices/$', PriceListView.as_view(), name='prices'),
    url(r'^news/$', NewsList.as_view(), name='news_list'),
    url(r'^news/(?P<slug>[-\w]+)/$', NewsDetail.as_view(), name='news'),
    url(r'^salary_stats/(?P<year>\d+)/$', SalaryStatList.as_view(), name='stat_list_year'),
    url(r'^salary_stats/$', SalaryStatList.as_view(), name='stat_list'),
    url(r'^mnenie-eksperta/$', ExpertNoteListView.as_view(), name='expert_note_list'),
    url(r'^mnenie-eksperta/(?P<slug>[-\w]+)/$', ExpertNoteDetailView.as_view(), name='expert_note'),
    url(r'^events/$', EventList.as_view(), name='events'),
    url(r'^events/(?P<slug>[-\w]+)/$', EventDetail.as_view(), name='event'),
]

job/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

from content.views import FullSearchView

urlpatterns = list()

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    url(r'^', include('job_catalog.urls', namespace='catalog')),
    url(r'^', include('content.urls', namespace='content')),
    url(r'^admin/', admin.site.urls),

    url(r'^search/', FullSearchView.as_view(), name='search'),
    url(r'^accounts/', include('users.accounts_urls')),
    url(r'^profile/', include('users.urls', namespace='profile')),
    url(r'^banner/', include('banner.urls', namespace='banner')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^polls/', include('poll.urls', namespace='poll')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

job_catalog/urls.py
from django.conf.urls import url

from job_catalog.forms import CVModelAndRegistrationForm
from job_catalog.models import CV, Vacancy
from job_catalog.views import IndexView, CreateAdvertRegistrationView, VacancyAndRegistrationForm, CreateCVView, \
    CreateVacancyView, MyCvList, MyVacancyList, CVEditView, VacancyEditView, GetCvInfo, GetVacancyInfo, ReplySuccess, \
    ReplyCv, ReplyVacancy, AddToFavorites, DeleteFromFavorites, MyFavorites, ToPrint
from yandex_job.views import YandexJobGate

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^create_cv_unregister/$', CreateAdvertRegistrationView.as_view(form_class=CVModelAndRegistrationForm,
                                                                         model=CV), name='cv_unregister'),
    url(r'^create_vacancy_unregister/$', CreateAdvertRegistrationView.as_view(form_class=VacancyAndRegistrationForm,
                                                                              model=Vacancy,
                                                                              template_name='create_vacancy.html'),
        name='vacancy_unregister'),
    url(r'^create_cv/$', CreateCVView.as_view(), name='cv_create'),
    url(r'^create_vacancy/$', CreateVacancyView.as_view(), name='vacancy_create'),
    url(r'^my_cv/$', MyCvList.as_view(), name='my_cv_list'),
    url(r'^my_vacancies/$', MyVacancyList.as_view(), name='my_vac_list'),
    url(r'^update_cv/(?P<pk>\d+)/$', CVEditView.as_view(), name='update_cv'),
    url(r'^update_vacancies/(?P<pk>\d+)/$', VacancyEditView.as_view(), name='update_vacancy'),
    url(r'^get_cv_info/(?P<pk>\d+)/$', GetCvInfo.as_view(), name='get_cv_info'),
    url(r'^get_vacancy_info/(?P<pk>\d+)/$', GetVacancyInfo.as_view(), name='get_vacancy_info'),
    url(r'^reply_cv/(?P<pk>\d+)/$', ReplyCv.as_view(), name='cv_reply'),
    url(r'^reply_vacancy/(?P<pk>\d+)/$', ReplyVacancy.as_view(), name='vac_reply'),
    url(r'^success_reply/$', ReplySuccess.as_view(), name='success_reply'),
    url(r'^add_to_fav/(?P<slug>\w+)/(?P<pk>\d+)/$', AddToFavorites.as_view(), name='add_fav'),
    url(r'^delete_to_fav/(?P<slug>\w+)/(?P<pk>\d+)/$', DeleteFromFavorites.as_view(), name='delete_fav'),
    url(r'^my_favorites/$', MyFavorites.as_view(), name='my_fav'),
    url(r'^to_print/(?P<slug>\w+)/(?P<pk>\d+)/$', ToPrint.as_view(), name='to_print'),
    url(r'^vacancy_gate/$', YandexJobGate.as_view()),
]

poll/urls.py
from django.conf.urls import url

from poll.views import PollIndexView, VoteAddView, AllPollListView

urlpatterns = [
    url(r'^$', PollIndexView.as_view(), name='index'),
    url(r'^all_polls$', AllPollListView.as_view(), name='polls_list'),
    url(r'^vote/(?P<pk>\d+)/$', VoteAddView.as_view(), name='vote'),
]

users/urls.py
from django.conf.urls import url

from users.views import ProfileView, ProfileChangePhoto, ProfileUpdate, SubscribeCreateView, MySubscribesListView, \
    MySubscribeDeleteView

urlpatterns = [
    url(r'^$', ProfileView.as_view(), name='profile'),
    url(r'^update_profile/$', ProfileUpdate.as_view(), name='profile_update'),
    url(r'^set_photo/$', ProfileChangePhoto.as_view(), name='profile_set_photo'),
    url(r'^create_subscribe/$', SubscribeCreateView.as_view(), name='create_subscribe'),
    url(r'^my_subscribes/$', MySubscribesListView.as_view(), name='my_subscribes'),
    url(r'^delete_subscribe/(?P<pk>\d+)/$', MySubscribeDeleteView.as_view(), name='delete_subscribe'),
]

templates/_cv_info.html
<div>
    <p class="p14">Образование: <b>{{ edu|default:"Не указано" }}</b></p>
</div>
<div>
    <p class="p14 p14_sub"><b>Навыки</b></p>
    <p class="p14">{{ skills|default:"Не указано" }}</p>
</div>
<div>
    <p class="p14 p14_sub"><b>Последнее место работы:</b></p>
    <p class="p14">{{ last_work|default:"Не указано" }}</p>
</div>
<div>
    <p class="p14 p14_sub"><b>Дата рождения:</b></p>
    <p class="p14">{{ birth_date }}</p>
</div>
<div>
    <p class="p14 p14_sub"><b>ФИО:</b> {{ fio }}</p>
    <p class="p14 p14_sub"><b>Телефон:</b> {{ phone }}</p>
    <p class="p14 p14_sub"><b>E-mail:</b> {{ email }}</p>
    <p class="p14 p14_sub"><a href="{% url 'catalog:to_print' 'cv' pk %}" target="_blank">Распечатать</a></p>
</div>

templates/base.html
{% load user_tags polls_tags content_tags menu_tags ads_tags %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% if meta_title %}{{ meta_title }}{% else %}{{ META_TITLE }}{% endif %}</title>
    <meta name="description" content="{% if meta_description %}{{ meta_description }}{% else %}{{ META_DESCRIPTION }}{% endif %}" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/1140_ed.css">
    <!--
    <link rel="stylesheet" href="{{ STATIC_URL }}css/main.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/form.css">
    -->
    <link rel="stylesheet" href="http://zesu.ru/main.css">
    <link rel="stylesheet" href="http://zesu.ru/form.css">
    <link rel="shortcut icon" href="{{ STATIC_URL }}favicon.ico" type="image/x-icon">
    {% block css %}
    {% endblock %}
</head>
<body>
<div class="header">
    <div class="container">
        <div class="row over_visible">
            <div class="col3 logo_rel">
                <a href="{% url 'catalog:index' %}"><img src="{{ STATIC_URL }}img/logo.jpg" alt=""></a>
            </div>
            <div class="col3 top_pad_lt">
                <p><a href="/?view=c" class="p16">Поиск резюме</a></p>
                <p><a href="/?view=v" class="p16">Поиск вакансий</a></p>
            </div>
            {% if request.user.is_authenticated %}
                <div class="col3 top_pad_lt">
                    <p><a href="{% url 'catalog:vacancy_create' %}" class="p16">Разместить вакансию</a></p>
                    <p><a href="{% url 'catalog:cv_create' %}" class="p16">Разместить резюме</a></p>
                </div>
            {% else %}
                <div class="col3 top_pad_lt">
                    <p><a href="{% url 'catalog:vacancy_create' %}" class="p16">Разместить вакансию</a></p>
                    <p><a href="{% url 'catalog:cv_unregister' %}" class="p16">Разместить резюме</a></p>
                </div>
            {% endif %}
            {% if request.user.is_authenticated %}
                <div class="col3 pullright right">
                    <p class="akk_lnk"><a href="{% url 'profile:profile' %}" class="p16">Личный кабинет</a></p>
                    <p class="akk_lnk"><a href="{% url 'logout' %}" class="p16">Выход</a></p>
                    {% get_fav_ad_count request.user as ad_count %}
                    <p class="fav_lnk"><a href="{% url 'catalog:my_fav' %}" class="p16">Избранное: (<span id="fav_count">{{ad_count}}</span>)</a></p>
                </div>
            {% else %}
                <div class="col3 pullright right">
                    <p class="akk_lnk"><a href="{% url 'login' %}" class="p16">Вход</a></p>
                    <p class="akk_lnk"><a href="{% url 'registration_variant' %}" class="p16">Регистрация</a></p>
                </div>
            {% endif %}
            <div class="clear"></div>
        </div>
        <div class="row">
            <div class="col3">
                <p class="p14">Кировская региональная<br>
                    газета о работе</p>
            </div>
            <div class="col8 pullright right">
                <form class="top_search" action="{% url 'search' %}">
                    <input type="search" name="q">
                    <button type="submit"><img src="{{ STATIC_URL }}img/ico_search.png" alt=""></button>
                </form>
                {% get_last_newspaper as news_paper %}
                {% if news_paper %}
                    <div class="btn_yel"><a href="{{ MEDIA_URL }}{{ news_paper.paper_file }}">Свежий выпуск от {{ news_paper.date_release|date:"d E Y" }} г</a></div>
                {% endif %}
                {% if request.user.is_authenticated and request.user.profile_employer %}
                    <div class="btn_black js_trigger2">Подписаться на резюме</div>
                {% else %}
                    <div class="btn_black js_trigger2">Подписаться на вакансии</div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<div class="clear"></div>
<div class="content">
    <div class="container">
        <div class="row over_visible">
            <div class="col3 left_nav">
                <ul class="nav_level1">
                    <li id="nav_ico1">
                        <a href="#">Об издании</a>
                        <div>
                            <ul class="nav_level2">
                                <li class="{% is_active menu_slug 'index' %}"><a href="{% url 'catalog:index' %}"><span>О газете</span></a></li>
                                <li class="{% is_active menu_slug 'feed' %}"><a href="{% url 'content:feedback' %}"><span>Отзывы клиентов</span></a></li>
                                <li class="{% is_active menu_slug 'partners' %}"><a href="{% url 'content:partners' %}"><span>Наши партнеры</span></a></li>
                                <li class="{% is_active menu_slug 'birthday' %}"><a href="{% url 'content:birth_day' %}"><span>Поздравления пртнеров</span></a></li>
                                <li class="{% is_active menu_slug 'posts' %}"><a href="{% url 'content:articles' %}"><span>Наши статьи</span></a></li>
                                <li class="{% is_active menu_slug 'news' %}"><a href="{% url 'content:news_list' %}"><span>Новости</span></a></li>
                            </ul>
                        </div>
                    </li>
                    <li class="{% is_active menu_slug 'archive' %}" id="nav_ico2"><a href="{% url 'content:archive' %}">Архив газеты</a></li>
                    <li class="{% is_active menu_slug 'qa' %}" id="nav_ico3"><a href="{% url 'content:qa_detail' %}">Юрист отвечает</a></li>
                    <li class="{% is_active menu_slug 'edu' %}" id="nav_ico4"><a href="{% url 'content:education' %}">Обучение</a></li>
                    <li class="{% is_active menu_slug 'prices' %}" id="nav_ico5"><a href="{% url 'content:prices' %}">Прайсы</a></li>
                    <li class="{% is_active menu_slug 'actions' %}" id="nav_ico6"><a href="{% url 'content:actions' %}">Акции</a></li>
                    <li class="{% is_active menu_slug 'poll' %}" id="nav_ico7"><a href="{% url 'poll:index' %}">Наши опросы</a></li>
                    <li class="{% is_active menu_slug 'stat' %}" id="nav_ico8"><a href="{% url 'content:stat_list' %}">Статистика зарплат</a></li>
                    <li class="{% is_active menu_slug 'contact' %}" id="nav_ico9"><a href="{% url 'content:contacts' %}">Контакты</a></li>
                </ul>
            </div>
            <div class="col3 left_links">
                {% block left_line %}
                {% endblock %}
            </div>
            <div class="col7 center_main">
                {% block center_line %}
                {% endblock %}
            </div>
            <div class="col3 right_links">
                {% block right_line %}
                {% endblock %}
            </div>
        </div>
    </div>
    <div class="clear"></div>
    {% block pagination %}

    {% endblock %}
    <div class="content_bottom">
        <div class="new_feat">
            <div class="new_feat_in">
                <h3>Почитать</h3>
                <a href="{% url 'content:expert_note_list' %}"><h4>Мнение эксперта</h4></a>

                <p class="p16">Статей: {% get_expert_counter %}</p>
                <a href="{% url 'content:news_list' %}"><h4>Новости</h4></a>
                <p class="p16">Статей: {% get_news_counter %}</p>
                <a href="{% url 'content:articles' %}"><h4>Статьи о наших клиентах</h4></a>
                <p class="p16">Статей: {% get_article_counter %}</p>
            </div>
        </div>
        <div class="new_feat">
            <div class="new_feat_in">
                <h3>События</h3>
                <a href="{% url 'content:birth_day' %}"><h4>Есть повод!</h4></a>
                <p class="p16">Дни рождения наших клиентов</p>
                <a href="{% url 'content:events' %}"><h4>Ярмарки вакансий и выставки</h4></a>
                <p class="p16">Мероприятия города</p>
            </div>
        </div>
        <div class="new_feat">
            <div class="new_feat_in quest_blc">
                {% render_poll_in_footer request %}
            </div>
        </div>
        <div class="clear"></div>
        <div class="promo_tx_wr">
            <div class="promo_tx">
                <p class="p14">Удобный привлекательный формат газеты А3, четкий рубрикатор делают издание понятным для кандидатов, недорогая стоимость в точках продаж 8 руб., правдивый еженедельный тираж в 3000 экземпляров и обширное бесплатное распространение делают газету доступной для читателей.</p>
                <p class="p14">Удобный привлекательный формат газеты А3, четкий рубрикатор делают издание понятным для кандидатов, недорогая стоимость в точках продаж 8 руб., правдивый еженедельный тираж в 3000 экземпляров и обширное бесплатное распространение делают газету доступной для читателей.</p>
                <p class="p14">
                    С октября 2012 года редакция газеты «Кадры города» запустила специальный четверговый выпуск издания. Этот номер целиком и полностью посвящен информации об открытых вакансиях и работе в Кирове. Свежие вакансии Кирова ждут Вас! Номер для тех, кому срочно нужны сотрудники и для тех, кто хочет быстро трудоустроиться, не откладывая поиск работы до понедельника.</p>
            </div>
        </div>
    </div>
</div>
<div class="clear"></div>
<div class="footer">
    <div class="container">
        <div class="row over_visible">
            <div class="col4 logo_rel">
                <img src="{{ STATIC_URL }}img/logo.jpg" alt="">
            </div>
            <div class="col3 ft_menu">
                <h3>Об издании</h3>
                <ul>
                    <li><a href="#">О газете</a></li>
                    <li><a href="#">Отзывы клиентов</a></li>
                    <li><a href="#">Наши партнеры</a></li>
                    <li><a href="#">Архив газеты</a></li>
                    <li><a href="#">Юрист отвечает</a></li>
                </ul>
            </div>
            <div class="col3 ft_menu ft_menu2">
                <ul>
                    <li><a href="#">Обучение</a></li>
                    <li><a href="#">Прайсы</a></li>
                    <li><a href="#">Акции</a></li>
                    <li><a href="#">Наши опросы</a></li>
                    <li><a href="#">Статистика зарплат</a></li>
                    <li><a href="#">Контакты</a></li>
                </ul>
            </div>
            <div class="col4 pullright right">
                <div><a href="tel:+78002222222" class="tel_footer">8-800-222-22-22</a></div>
                <div><a href="tel:+788332210360" class="tel_footer">8(8332)-21-03-60</a></div>
                <p class="ft_addr">г.Киров, ул. К. Маркса, 18 оф. 203,204</p>
                <div class="ft_socials">
                    <a href="#"><img src="{{ STATIC_URL }}img/ico_socials.jpg" alt=""></a>
                    <a href="#"><img src="{{ STATIC_URL }}img/ico_gplay.jpg" alt=""></a>
                </div>
            </div>
        </div>
    </div>
    <div class="clear"></div>
</div>
{% block modal %}
{% endblock %}
    {% get_categories as categories %}
    <div class="modal" id="subscribe-modal" style="display: none">
		<a href="#" class="close"><img src="{{ STATIC_URL }}img/cross.png" alt=""></a>
		<div>
			<form method="POST" id="form_1" class="formv" action="{% url 'profile:create_subscribe' %}"
                  enctype="multipart/form-data">
                {% csrf_token %}
                <input type="hidden" name="redirect" value="{{ request.path }}">
                <label for="slug">
                    Тип подписки
                </label>
                <select name="slug" id="slug">
                    <option value="0">Вакансии</option>
                    <option value="1">Резюме</option>
                </select>
                <label for="category">
                    Сфера деятельности
                </label>
                <select name="category" id="">
                    {% for cat in categories.cat_list %}
                        <option value="{{ cat.pk }}">{{ cat.name }}</option>
                    {% endfor %}
                </select>
                <button type="submit" class="wide_yellow">Подписаться</button>
			</form>
		</div>
    </div>
<script src="{{ STATIC_URL }}js/jquery-3.2.1.min.js"></script>
<script src="{{ STATIC_URL }}js/modal.js"></script>
<script src="{{ STATIC_URL }}js/script.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.js"></script>
<script>
    var defaults_fancy = {


    infobar : true,

    toolbar : true,

    buttons : [
        'fullScreen',
        'close'
    ],


    afterShow:
        function( instance, current ) {
             var url = current.opts.$orig.data('url');
             $.get(url);
        },




    // Internationalization
    // ============

    lang : 'ru',
    i18n : {
        'ru' : {
            CLOSE       : 'Закрыть',
            ERROR       : 'Ошибка загрузки контента',
            FULL_SCREEN : 'На весь экран',
            THUMBS      : 'Превью',
            DOWNLOAD    : 'Загрузить',
            ZOOM        : 'Увеличить'
        }
    }

};
    $("[data-fancybox]").fancybox(defaults_fancy);
</script>
{% block bottom_js %}
{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load banners_tag ads_tags %}
{% block left_line %}
    {% get_banners request.path as banners %}
    {% autoescape off %}
        {{ banners.0|render_banner }}
        {{ banners.1|render_banner }}
        {{ banners.2|render_banner }}
        {{ banners.3|render_banner }}
        {{ banners.4|render_banner }}
        {{ banners.5|render_banner }}
        {{ banners.6|render_banner }}
        {{ banners.7|render_banner }}
        {{ banners.8|render_banner }}
        {{ banners.9|render_banner }}
        {{ banners.10|render_banner }}
        {{ banners.11|render_banner }}
        {{ banners.12|render_banner }}
        {{ banners.13|render_banner }}
        {{ banners.14|render_banner }}
        {{ banners.15|render_banner }}
        {{ banners.16|render_banner }}
        {{ banners.17|render_banner }}
        {{ banners.18|render_banner }}
        {{ banners.19|render_banner }}
    {% endautoescape %}
{% endblock %}
{% block center_line %}
    <div class="row over_visible">
        {% get_categories as categories %}
        <div class="col8">
            <div class="form_m_wrap">
                <p class="p19">СОИСКАТЕЛЮ</p>
                <p class="p12">Поиск вакансий</p>
                <form>
                    <input type="search" name="qv" placeholder="Например: Менеджер" {% if request.GET.qv %}value="{{ request.GET.qv }}"{% endif %}>
                    <button class="btn_yel btn_sm">НАЙТИ</button>
                </form>
                <a href="#" class="js_show_list p12 f1_dark f1_dark_under">Сферы деятельности (<b>{{ categories.count }}</b>)</a>
                <div class="js_list_hidden" style="display: none;">
                    <ul>
                        {% for cat in categories.cat_list %}
                            <li><a href="/?view=v&cat={{ cat.pk }}">{{ cat.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                {% if  request.user.is_authenticated %}
                    <a href="{% url 'catalog:cv_create' %}" class="btn_yel btn_wide">Разместить резюме</a>
                {% else %}
                    <a href="{% url 'catalog:cv_unregister' %}" class="btn_yel btn_wide">Разместить резюме</a>
                {% endif %}
                <div class="right p12 f1_dark">Всего
                    <a class="f1_dark_under" href="?view=v">вакансий:</a><b> {% get_vacancy_count %}</b>
                </div>
            </div>
        </div>
        <div class="col8">
            <div class="form_m_wrap">
                <p class="p19">РАБОТОДАТЕЛЮ</p>
                <p class="p12">Поиск резюме</p>
                <form>
                    <input type="search" name="qc" placeholder="Например: Бухгалтер" {% if request.GET.qc %}value="{{ request.GET.qc }}"{% endif %}>
                    <button class="btn_yel btn_sm">НАЙТИ</button>
                </form>
                <a href="#" class="js_show_list p12 f1_dark f1_dark_under">Сферы деятельности (<b>{{ categories.count }}</b>)</a>
                <div class="js_list_hidden" style="display: none;">
                    <ul>
                        {% for cat in categories.cat_list %}
                            <li><a href="?view=c&cat={{ cat.pk }}">{{ cat.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                {% if request.user.is_authenticated %}
                    <a href="{% url 'catalog:vacancy_create' %}" class="btn_black btn_wide">Разместить вакансию</a>
                {% else %}
                    <a href="{% url 'catalog:vacancy_unregister' %}" class="btn_black btn_wide">Разместить вакансию</a>
                {% endif %}
                <div class="right p12 f1_dark">Всего
                    <a class="f1_dark_under" href="?view=c">резюме:</a><b> {% get_cv_count %}</b>
                </div>
            </div>
        </div>
    </div>
    <div class="clear"></div>
    <div class="row over_visible main_cont_wrap">
        <div class="search_head">
            <div class="col8">
                <p class="p14">Найдено <b>{{ paginator.count }} </b>{% if is_vacancy %} вакансий{% else %} резюме{% endif %}</p>
            </div>
            <div class="col8 right">
                <p class="p14">Сортировать по:
                    <select name="view" id="">
                        <option value="v" {% if is_vacancy %}selected{% endif %}>Вакансии</option>
                        <option value="c" {% if not is_vacancy %}selected{% endif %}>Резюме</option>
                    </select>
                </p>
            </div>
        </div>
    </div>

    <div class="src_result col16">
        {% if is_vacancy %}
            {% render_vacancy_list object_list %}
        {% else %}
            {% render_cv_list object_list %}
        {% endif %}
    </div>
{% endblock %}
{% block pagination %}
<div class="pagination center">
    {% if page_obj.paginator.num_pages > 1 %}
        <ul>
            {% for page in page_obj.pages %}
                <li>
                    {% if page %}
                        {% ifequal page page_obj.number %}
                            <span>{{ page }}</span>
                        {% else %}
                            <a href="?{{ page.querystring }}">{{ page }}</a>
                        {% endifequal %}
                    {% else %}
                        ...
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% endif %}
</div>
{% endblock %}
{% block right_line %}
    {% get_banners request.path as banners %}
    {% autoescape off %}
        {{ banners.20|render_banner }}
        {{ banners.21|render_banner }}
        {{ banners.22|render_banner }}
        {{ banners.23|render_banner }}
        {{ banners.24|render_banner }}
        {{ banners.25|render_banner }}
        {{ banners.26|render_banner }}
        {{ banners.27|render_banner }}
        {{ banners.28|render_banner }}
        {{ banners.29|render_banner }}
        {{ banners.30|render_banner }}
        {{ banners.31|render_banner }}
        {{ banners.32|render_banner }}
        {{ banners.33|render_banner }}
        {{ banners.34|render_banner }}
        {{ banners.35|render_banner }}
        {{ banners.36|render_banner }}
        {{ banners.37|render_banner }}
        {{ banners.38|render_banner }}
        {{ banners.39|render_banner }}
    {% endautoescape %}
{% endblock %}
{% block modal %}
    <div class="modal" id="test-modal" style="display: none">
		<a href="#" class="close"><img src="{{ STATIC_URL }}img/cross.png" alt=""></a>
		<div>
			<form method="POST" id="form_1" class="formv" action="{% url 'profile:profile_set_photo' %}"
                  enctype="multipart/form-data">
                {% csrf_token %}
                <input type="file" name="photo">
                <button type="submit" class="wide_yellow">Сменить фото</button>
			</form>
		</div>
    </div>
{% endblock %}